package com.rpa.financial_intelligence_system.service;

import com.fasterxml.jackson.databind.*;import org.springframework.stereotype.Service;import java.io.*;import java.net.URI;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.time.Duration;import java.util.*;
@Service
public class AiService {
 private final ObjectMapper mapper;private final ModelConfigService configs;private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(15)).build();public AiService(ObjectMapper mapper,ModelConfigService configs){this.mapper=mapper;this.configs=configs;}
 public Map<String,Object> chat(List<Map<String,String>> messages,String model,Double temperature){var c=configs.active();ensure(c.chatApiKey(),"语言模型");var body=new LinkedHashMap<String,Object>();body.put("model",blank(model)?c.chatModel():model);body.put("messages",messages);body.put("temperature",temperature==null?c.temperature():temperature);body.put("max_tokens",c.maxTokens());JsonNode out=post(c.chatApiUrl(),c.chatApiKey(),body);return Map.of("content",out.path("choices").path(0).path("message").path("content").asText(),"model",out.path("model").asText(c.chatModel()),"usage",mapper.convertValue(out.path("usage"),Map.class));}
 @FunctionalInterface public interface StreamListener{void onDelta(String content)throws Exception;}
 public Map<String,Object> chatStream(List<Map<String,String>> messages,String model,Double temperature,StreamListener listener){
  var c=configs.active();ensure(c.chatApiKey(),"语言模型");String selected=blank(model)?c.chatModel():model;
  var body=new LinkedHashMap<String,Object>();body.put("model",selected);body.put("messages",messages);body.put("temperature",temperature==null?c.temperature():temperature);body.put("max_tokens",c.maxTokens());body.put("stream",true);body.put("stream_options",Map.of("include_usage",true));
  try{
   var request=HttpRequest.newBuilder(URI.create(c.chatApiUrl())).timeout(Duration.ofMinutes(3)).header("Authorization","Bearer "+c.chatApiKey()).header("Content-Type","application/json").header("Accept","text/event-stream").POST(HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body))).build();
   var response=http.send(request,HttpResponse.BodyHandlers.ofInputStream());
   if(response.statusCode()/100!=2){try(var input=response.body()){throw new IllegalArgumentException("模型服务调用失败（HTTP "+response.statusCode()+"）："+safe(new String(input.readNBytes(1000),StandardCharsets.UTF_8)));}}
   String currentModel=selected;Map<String,Object> usage=Map.of();StringBuilder content=new StringBuilder();
   try(var reader=new BufferedReader(new InputStreamReader(response.body(),StandardCharsets.UTF_8))){String line;while((line=reader.readLine())!=null){if(line.isBlank()||!line.startsWith("data:"))continue;String data=line.substring(5).trim();if(data.equals("[DONE]"))break;JsonNode event=mapper.readTree(data);if(event.has("error"))throw new IllegalArgumentException(event.path("error").path("message").asText("模型流式响应失败"));if(event.hasNonNull("model"))currentModel=event.path("model").asText(currentModel);JsonNode delta=event.path("choices").path(0).path("delta").path("content");if(delta.isTextual()&&!delta.asText().isEmpty()){String chunk=delta.asText();content.append(chunk);listener.onDelta(chunk);}if(event.has("usage")&&!event.path("usage").isNull())usage=mapper.convertValue(event.path("usage"),Map.class);}}
   var result=new LinkedHashMap<String,Object>();result.put("content",content.toString());result.put("model",currentModel);result.put("usage",usage);return result;
  }catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalArgumentException("模型调用已中断");}catch(Exception e){if(e instanceof IllegalArgumentException illegal)throw illegal;throw new IllegalArgumentException("无法连接模型服务："+e.getMessage());}
 }
 public List<Double> embedding(String text){var c=configs.active();ensure(c.vectorApiKey(),"向量化服务");JsonNode out=post(c.vectorBaseUrl()+c.vectorApiPath(),c.vectorApiKey(),Map.of("model",c.embeddingModel(),"input",text));var list=new ArrayList<Double>();out.path("data").path(0).path("embedding").forEach(x->list.add(x.asDouble()));if(list.size()!=c.embeddingDimensions())throw new IllegalArgumentException("Embedding 实际维度 "+list.size()+" 与配置维度 "+c.embeddingDimensions()+" 不一致");return list;}
 public Map<String,Object> testChat(){var c=configs.active();ensure(c.chatApiKey(),"语言模型");long start=System.currentTimeMillis();JsonNode out=post(c.chatApiUrl(),c.chatApiKey(),Map.of("model",c.chatModel(),"messages",List.of(Map.of("role","user","content","只回复 OK")),"max_tokens",8,"temperature",0));return Map.of("success",true,"service","chat","model",out.path("model").asText(c.chatModel()),"latencyMs",System.currentTimeMillis()-start);}
 public Map<String,Object> testVector(){var c=configs.active();long start=System.currentTimeMillis();var vector=embedding("向量服务连接测试");return Map.of("success",true,"service","vector","model",c.embeddingModel(),"dimensions",vector.size(),"latencyMs",System.currentTimeMillis()-start);}
 private JsonNode post(String url,String key,Object body){try{var req=HttpRequest.newBuilder(URI.create(url)).timeout(Duration.ofSeconds(90)).header("Authorization","Bearer "+key).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(mapper.writeValueAsString(body))).build();var res=http.send(req,HttpResponse.BodyHandlers.ofString());if(res.statusCode()/100!=2)throw new IllegalArgumentException("模型服务调用失败（HTTP "+res.statusCode()+"）："+safe(res.body()));return mapper.readTree(res.body());}catch(InterruptedException e){Thread.currentThread().interrupt();throw new IllegalArgumentException("模型调用已中断");}catch(Exception e){if(e instanceof IllegalArgumentException i)throw i;throw new IllegalArgumentException("无法连接模型服务："+e.getMessage());}}
 private void ensure(String key,String name){if(blank(key))throw new IllegalArgumentException(name+"尚未配置 API Key");}private boolean blank(String s){return s==null||s.isBlank();}private String safe(String s){return s==null?"未知错误":s.substring(0,Math.min(500,s.length()));}
}
