package com.rpa.financial_intelligence_system.service;

import org.springframework.beans.factory.annotation.Value;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.util.*;

@Service
public class ModelConfigService {
 public record Config(long id,String name,String provider,String chatApiUrl,String chatApiKey,String chatModel,double temperature,int maxTokens,String vectorBaseUrl,String vectorApiPath,String vectorApiKey,String embeddingModel,int embeddingDimensions,int vectorConcurrency,boolean enabled){}
 private final JdbcClient jdbc;private final SecretCryptoService crypto;private final String envKey;
 public ModelConfigService(JdbcClient jdbc,SecretCryptoService crypto,@Value("${app.ai.api-key:}")String envKey){this.jdbc=jdbc;this.crypto=crypto;this.envKey=envKey;}
 public Config active(){var rows=jdbc.sql("SELECT * FROM ai_model_config WHERE enabled ORDER BY id LIMIT 1").query().listOfRows();if(rows.isEmpty())throw new IllegalArgumentException("没有启用的模型配置，请管理员先在模型设置中启用服务");var r=rows.getFirst();String chatKey=crypto.decrypt((String)r.get("chat_api_key_encrypted"));String vectorKey=crypto.decrypt((String)r.get("vector_api_key_encrypted"));if(chatKey.isBlank())chatKey=envKey;if(vectorKey.isBlank())vectorKey=envKey;return map(r,chatKey,vectorKey);}
 public List<Map<String,Object>> list(){return jdbc.sql("SELECT id,name,provider,chat_api_url,chat_model,temperature,max_tokens,vector_base_url,vector_api_path,embedding_model,embedding_dimensions,vector_concurrency,enabled,chat_api_key_encrypted IS NOT NULL has_chat_api_key,vector_api_key_encrypted IS NOT NULL has_vector_api_key,updated_at FROM ai_model_config ORDER BY id").query().listOfRows();}
 @Transactional public long save(Long id,String name,String provider,String chatApiUrl,String chatApiKey,String chatModel,Double temperature,Integer maxTokens,String vectorBaseUrl,String vectorApiPath,String vectorApiKey,String embeddingModel,Integer dimensions,Integer concurrency,Boolean enabled){
  if(dimensions==null||dimensions!=1024)throw new IllegalArgumentException("当前知识库向量维度固定为 1024");if(enabled==null||enabled){if(id==null)jdbc.sql("UPDATE ai_model_config SET enabled=FALSE").update();else jdbc.sql("UPDATE ai_model_config SET enabled=FALSE WHERE id<>:id").param("id",id).update();}
  String chatEncrypted=isNewKey(chatApiKey)?crypto.encrypt(chatApiKey):null,vectorEncrypted=isNewKey(vectorApiKey)?crypto.encrypt(vectorApiKey):null;
  if(id==null)return jdbc.sql("INSERT INTO ai_model_config(name,provider,chat_api_url,chat_api_key_encrypted,chat_model,temperature,max_tokens,vector_base_url,vector_api_path,vector_api_key_encrypted,embedding_model,embedding_dimensions,vector_concurrency,enabled) VALUES(:n,:p,:cu,:ck,:cm,:t,:mt,:vu,:vp,:vk,:em,:d,:vc,:on) RETURNING id").param("n",name).param("p",provider).param("cu",cleanUrl(chatApiUrl)).param("ck",chatEncrypted).param("cm",chatModel).param("t",temperature).param("mt",maxTokens).param("vu",cleanUrl(vectorBaseUrl)).param("vp",cleanPath(vectorApiPath)).param("vk",vectorEncrypted).param("em",embeddingModel).param("d",dimensions).param("vc",concurrency).param("on",enabled==null||enabled).query(Long.class).single();
  String extra=(chatEncrypted!=null?",chat_api_key_encrypted=:ck":"")+(vectorEncrypted!=null?",vector_api_key_encrypted=:vk":"");var q=jdbc.sql("UPDATE ai_model_config SET name=:n,provider=:p,chat_api_url=:cu,chat_model=:cm,temperature=:t,max_tokens=:mt,vector_base_url=:vu,vector_api_path=:vp,embedding_model=:em,embedding_dimensions=:d,vector_concurrency=:vc,enabled=:on,updated_at=now()"+extra+" WHERE id=:id").param("n",name).param("p",provider).param("cu",cleanUrl(chatApiUrl)).param("cm",chatModel).param("t",temperature).param("mt",maxTokens).param("vu",cleanUrl(vectorBaseUrl)).param("vp",cleanPath(vectorApiPath)).param("em",embeddingModel).param("d",dimensions).param("vc",concurrency).param("on",enabled==null||enabled).param("id",id);if(chatEncrypted!=null)q.param("ck",chatEncrypted);if(vectorEncrypted!=null)q.param("vk",vectorEncrypted);q.update();return id;
 }
 public void delete(long id){if(jdbc.sql("SELECT enabled FROM ai_model_config WHERE id=:id").param("id",id).query(Boolean.class).optional().orElse(false))throw new IllegalArgumentException("当前启用的配置不能删除");jdbc.sql("DELETE FROM ai_model_config WHERE id=:id").param("id",id).update();}
 private Config map(Map<String,Object>r,String ck,String vk){return new Config(((Number)r.get("id")).longValue(),(String)r.get("name"),(String)r.get("provider"),(String)r.get("chat_api_url"),ck,(String)r.get("chat_model"),((BigDecimal)r.get("temperature")).doubleValue(),((Number)r.get("max_tokens")).intValue(),(String)r.get("vector_base_url"),(String)r.get("vector_api_path"),vk,(String)r.get("embedding_model"),((Number)r.get("embedding_dimensions")).intValue(),((Number)r.get("vector_concurrency")).intValue(),(Boolean)r.get("enabled"));}
 private boolean isNewKey(String s){return s!=null&&!s.isBlank()&&!s.contains("****");}private String cleanUrl(String s){return s==null?"":s.replaceAll("/$","");}private String cleanPath(String s){return s==null||s.isBlank()?"/v1/embeddings":(s.startsWith("/")?s:"/"+s);}
}
