package com.rpa.financial_intelligence_system.service;

import io.minio.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import java.io.*; import java.nio.file.*; import java.time.*; import java.util.*;

@Service
public class StorageService {
 public record Config(long id,String type,String localPath,String endpoint,String accessKey,String secretKey,String bucket,String region){}
 private final JdbcClient jdbc; private final SecretCryptoService crypto; private final Path projectRoot;
 public StorageService(JdbcClient jdbc,SecretCryptoService crypto,@Value("${user.dir}")String root){this.jdbc=jdbc;this.crypto=crypto;this.projectRoot=Path.of(root).toAbsolutePath().normalize();}
 public Config active(){var r=jdbc.sql("SELECT * FROM sys_storage_config ORDER BY id LIMIT 1").query().singleRow();return new Config(((Number)r.get("id")).longValue(),(String)r.get("storage_type"),(String)r.get("local_path"),(String)r.get("minio_endpoint"),(String)r.get("minio_access_key"),crypto.decrypt((String)r.get("minio_secret_key_encrypted")),(String)r.get("minio_bucket"),(String)r.get("minio_region"));}
 public Map<String,Object> settings(){var c=active();var m=new LinkedHashMap<String,Object>();m.put("id",c.id());m.put("storageType",c.type());m.put("localPath",c.localPath());m.put("minioEndpoint",c.endpoint());m.put("minioAccessKey",c.accessKey());m.put("hasMinioSecret",c.secretKey()!=null&&!c.secretKey().isBlank());m.put("minioBucket",c.bucket());m.put("minioRegion",c.region());return m;}
 @Transactional public void save(String type,String localPath,String endpoint,String accessKey,String secret,String bucket,String region,long userId){String encrypted=secret!=null&&!secret.isBlank()&&!secret.contains("*")?crypto.encrypt(secret):null;var sql="UPDATE sys_storage_config SET storage_type=:t,local_path=:l,minio_endpoint=:e,minio_access_key=:a,minio_bucket=:b,minio_region=:r,updated_by=:u,updated_at=now()"+(encrypted==null?"":",minio_secret_key_encrypted=:s")+" WHERE id=(SELECT id FROM sys_storage_config ORDER BY id LIMIT 1)";var q=jdbc.sql(sql).param("t",type).param("l",localPath==null||localPath.isBlank()?"data/uploads":localPath).param("e",endpoint).param("a",accessKey).param("b",bucket).param("r",region).param("u",userId);if(encrypted!=null)q.param("s",encrypted);q.update();}
 public Map<String,Object> test(){var c=active();try{if(c.type().equals("LOCAL")){Path p=localRoot(c);Files.createDirectories(p);if(!Files.isWritable(p))throw new IllegalStateException("目录不可写");return Map.of("success",true,"type","LOCAL","path",p.toString());}var client=minio(c);boolean exists=client.bucketExists(BucketExistsArgs.builder().bucket(c.bucket()).build());if(!exists)client.makeBucket(MakeBucketArgs.builder().bucket(c.bucket()).region(blank(c.region())?null:c.region()).build());return Map.of("success",true,"type","MINIO","bucket",c.bucket());}catch(Exception e){throw new IllegalArgumentException("存储连接失败："+e.getMessage());}}
 public Map<String,Object> upload(MultipartFile file,long userId)throws Exception{if(file.isEmpty())throw new IllegalArgumentException("文件不能为空");var c=active();String safe=Optional.ofNullable(file.getOriginalFilename()).orElse("file").replaceAll("[^a-zA-Z0-9._\\-\\u4e00-\\u9fa5]","_");String name=LocalDate.now()+"/"+UUID.randomUUID()+"_"+safe,objectKey,bucket=null;if(c.type().equals("LOCAL")){Path root=localRoot(c),target=root.resolve(name).normalize();if(!target.startsWith(root))throw new IllegalArgumentException("非法文件路径");Files.createDirectories(target.getParent());file.transferTo(target);objectKey=projectRoot.relativize(target).toString();}else{var client=minio(c);if(!client.bucketExists(BucketExistsArgs.builder().bucket(c.bucket()).build()))client.makeBucket(MakeBucketArgs.builder().bucket(c.bucket()).build());try(InputStream in=file.getInputStream()){client.putObject(PutObjectArgs.builder().bucket(c.bucket()).object(name).stream(in,file.getSize(),-1).contentType(file.getContentType()).build());}objectKey=name;bucket=c.bucket();}long id=jdbc.sql("INSERT INTO sys_file(original_name,object_key,storage_type,bucket,content_type,size_bytes,uploader_id) VALUES(:n,:k,:t,:b,:c,:s,:u) RETURNING id").param("n",safe).param("k",objectKey).param("t",c.type()).param("b",bucket).param("c",file.getContentType()).param("s",file.getSize()).param("u",userId).query(Long.class).single();return Map.of("id",id,"name",safe,"size",file.getSize());}
 public Resource download(Map<String,Object> f)throws Exception{if("LOCAL".equals(f.get("storage_type"))){Path p=projectRoot.resolve((String)f.get("object_key")).normalize();if(!p.startsWith(projectRoot)||!Files.exists(p))throw new FileNotFoundException("文件不存在");return new FileSystemResource(p);}var c=active();InputStream in=minio(c).getObject(GetObjectArgs.builder().bucket((String)f.get("bucket")).object((String)f.get("object_key")).build());return new InputStreamResource(in);}
 public void delete(Map<String,Object> f)throws Exception{if("LOCAL".equals(f.get("storage_type")))Files.deleteIfExists(projectRoot.resolve((String)f.get("object_key")).normalize());else{var c=active();minio(c).removeObject(RemoveObjectArgs.builder().bucket((String)f.get("bucket")).object((String)f.get("object_key")).build());}jdbc.sql("UPDATE sys_file SET status='DELETED',updated_at=now() WHERE id=:id").param("id",f.get("id")).update();}
 private Path localRoot(Config c){Path p=Path.of(c.localPath());return (p.isAbsolute()?p:projectRoot.resolve(p)).normalize();}
 private MinioClient minio(Config c){if(blank(c.endpoint())||blank(c.accessKey())||blank(c.secretKey())||blank(c.bucket()))throw new IllegalArgumentException("MinIO 配置不完整");return MinioClient.builder().endpoint(c.endpoint()).credentials(c.accessKey(),c.secretKey()).build();}
 private boolean blank(String s){return s==null||s.isBlank();}
}
