package com.rpa.financial_intelligence_system.controller;

import com.rpa.financial_intelligence_system.common.ApiResponse; import com.rpa.financial_intelligence_system.service.StorageService; import com.rpa.financial_intelligence_system.service.OfficePreviewService;
import io.swagger.v3.oas.annotations.*; import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank;
import org.springframework.core.io.Resource; import org.springframework.http.*; import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.util.*;

@Tag(name="文件中心",description="本地与 MinIO/S3 文件存储、上传下载和文件管理") @RestController @RequestMapping("/api")
public class FileController {
 private final JdbcClient jdbc; private final StorageService storage; private final OfficePreviewService officePreview; public FileController(JdbcClient jdbc,StorageService storage,OfficePreviewService officePreview){this.jdbc=jdbc;this.storage=storage;this.officePreview=officePreview;}
 record StorageReq(@NotBlank String storageType,String localPath,String minioEndpoint,String minioAccessKey,String minioSecretKey,String minioBucket,String minioRegion){}
 @Operation(summary="查询文件存储设置") @GetMapping("/storage/settings") @PreAuthorize("hasAuthority('storage:settings')") ApiResponse<?> settings(){return ApiResponse.ok(storage.settings());}
 @Operation(summary="保存文件存储设置") @PutMapping("/storage/settings") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> save(@Valid @RequestBody StorageReq q,Authentication a){storage.save(q.storageType(),q.localPath(),q.minioEndpoint(),q.minioAccessKey(),q.minioSecretKey(),q.minioBucket(),q.minioRegion(),uid(a));return ApiResponse.ok();}
 @Operation(summary="测试当前存储连接") @PostMapping("/storage/settings/test") @PreAuthorize("hasAuthority('storage:settings')") ApiResponse<?> test(){return ApiResponse.ok(storage.test());}
 @Operation(summary="文件列表") @GetMapping("/files") @PreAuthorize("hasAuthority('file:list')") ApiResponse<?> files(@RequestParam(defaultValue="")String keyword){return ApiResponse.ok(jdbc.sql("SELECT f.*,u.nickname uploader_name FROM sys_file f LEFT JOIN sys_user u ON u.id=f.uploader_id WHERE f.status='ACTIVE' AND (:k='' OR f.original_name ILIKE '%'||:k||'%') ORDER BY f.id DESC").param("k",keyword).query().listOfRows());}
 @Operation(summary="上传文件") @PostMapping(value="/files",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) @PreAuthorize("hasAuthority('file:list')") ApiResponse<?> upload(@RequestPart("file")MultipartFile file,Authentication a)throws Exception{return ApiResponse.ok(storage.upload(file,uid(a)));}
 @Operation(summary="下载文件") @GetMapping("/files/{id}/download") @PreAuthorize("hasAuthority('file:list')") ResponseEntity<Resource> download(@PathVariable long id)throws Exception{var f=file(id);String name=URLEncoder.encode((String)f.get("original_name"),StandardCharsets.UTF_8).replace("+","%20");return ResponseEntity.ok().contentType(MediaType.parseMediaType(Optional.ofNullable((String)f.get("content_type")).orElse("application/octet-stream"))).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename*=UTF-8''"+name).contentLength(((Number)f.get("size_bytes")).longValue()).body(storage.download(f));}
 @Operation(summary="在线预览文件原文") @GetMapping("/files/{id}/preview") @PreAuthorize("hasAuthority('file:list')") ResponseEntity<Resource> preview(@PathVariable long id)throws Exception{var f=file(id);String name=URLEncoder.encode((String)f.get("original_name"),StandardCharsets.UTF_8).replace("+","%20");return ResponseEntity.ok().contentType(safeType((String)f.get("content_type"))).header(HttpHeaders.CONTENT_DISPOSITION,"inline; filename*=UTF-8''"+name).header("X-Content-Type-Options","nosniff").contentLength(((Number)f.get("size_bytes")).longValue()).body(storage.download(f));}
 @Operation(summary="将 Word、Excel、PPT 转为 PDF 预览") @GetMapping(value="/files/{id}/preview-pdf",produces=MediaType.APPLICATION_PDF_VALUE) @PreAuthorize("hasAuthority('file:list')") ResponseEntity<Resource> previewPdf(@PathVariable long id)throws Exception{var f=file(id);if(!officePreview.supports((String)f.get("original_name")))throw new IllegalArgumentException("该文件类型无需 Office 转换");var pdf=officePreview.pdf(f);return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,"inline").header("X-Content-Type-Options","nosniff").contentLength(pdf.contentLength()).body(pdf);}
 @Operation(summary="删除文件") @DeleteMapping("/files/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> delete(@PathVariable long id)throws Exception{storage.delete(file(id));officePreview.evict(id);return ApiResponse.ok();}
 private Map<String,Object> file(long id){var rows=jdbc.sql("SELECT * FROM sys_file WHERE id=:id AND status='ACTIVE'").param("id",id).query().listOfRows();if(rows.isEmpty())throw new IllegalArgumentException("文件不存在");return rows.getFirst();}
 private MediaType safeType(String value){try{return MediaType.parseMediaType(Optional.ofNullable(value).filter(v->!v.isBlank()).orElse("application/octet-stream"));}catch(Exception ignored){return MediaType.APPLICATION_OCTET_STREAM;}}
 private long uid(Authentication a){return jdbc.sql("SELECT id FROM sys_user WHERE username=:u").param("u",a.getName()).query(Long.class).single();}
}
