package com.rpa.financial_intelligence_system.controller;

import com.rpa.financial_intelligence_system.common.ApiResponse;
import jakarta.validation.Valid; import jakarta.validation.constraints.*;
import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
import java.util.*;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.Operation;
import com.rpa.financial_intelligence_system.service.RedisSecurityService;

@Tag(name="系统管理") @RestController @RequestMapping("/api/system")
public class SystemController {
 private final JdbcClient jdbc; private final PasswordEncoder encoder; private final RedisSecurityService redis;
 public SystemController(JdbcClient jdbc,PasswordEncoder encoder,RedisSecurityService redis){this.jdbc=jdbc;this.encoder=encoder;this.redis=redis;}
 record UserForm(@NotBlank String username,String password,@NotBlank String nickname,@Email String email,String phone,Long departmentId,Boolean status,List<Long> roleIds){}
 record RoleForm(@NotBlank String name,@NotBlank String code,String description,Boolean status,List<Long> menuIds){}
 record MenuForm(Long parentId,@NotBlank String name,String path,String icon,String permission,String type,Integer sortOrder,Boolean visible){}
 record DeptForm(Long parentId,@NotBlank String name,String leader,String phone,Integer sortOrder,Boolean status){}

 @GetMapping("/users") @PreAuthorize("hasAuthority('system:user:list')") ApiResponse<?> users(@RequestParam(defaultValue="")String keyword){var rows=jdbc.sql("SELECT u.id,u.username,u.nickname,u.email,u.phone,u.department_id,d.name department_name,u.status,u.created_at,COALESCE(string_agg(r.name,','),'') role_names FROM sys_user u LEFT JOIN sys_department d ON d.id=u.department_id LEFT JOIN sys_user_role ur ON ur.user_id=u.id LEFT JOIN sys_role r ON r.id=ur.role_id WHERE (:k='' OR u.username ILIKE '%'||:k||'%' OR u.nickname ILIKE '%'||:k||'%') GROUP BY u.id,d.name ORDER BY u.id").param("k",keyword).query().listOfRows();rows.forEach(x->x.put("online",redis.online((String)x.get("username"))));return ApiResponse.ok(rows);}
 @PostMapping("/users") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") @Transactional ApiResponse<?> addUser(@Valid @RequestBody UserForm f){if(f.password()==null||f.password().length()<6)throw new IllegalArgumentException("密码至少 6 位");long id=jdbc.sql("INSERT INTO sys_user(username,password,nickname,email,phone,department_id,status) VALUES(:u,:p,:n,:e,:ph,:d,:s) RETURNING id").param("u",f.username()).param("p",encoder.encode(f.password())).param("n",f.nickname()).param("e",f.email()).param("ph",f.phone()).param("d",f.departmentId()).param("s",f.status()==null||f.status()).query(Long.class).single();setUserRoles(id,f.roleIds());return ApiResponse.ok(Map.of("id",id));}
 @PutMapping("/users/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") @Transactional ApiResponse<?> editUser(@PathVariable long id,@Valid @RequestBody UserForm f){jdbc.sql("UPDATE sys_user SET username=:u,nickname=:n,email=:e,phone=:ph,department_id=:d,status=:s,updated_at=now() WHERE id=:id").param("u",f.username()).param("n",f.nickname()).param("e",f.email()).param("ph",f.phone()).param("d",f.departmentId()).param("s",f.status()==null||f.status()).param("id",id).update();if(f.password()!=null&&!f.password().isBlank())jdbc.sql("UPDATE sys_user SET password=:p WHERE id=:id").param("p",encoder.encode(f.password())).param("id",id).update();setUserRoles(id,f.roleIds());return ApiResponse.ok();}
 @DeleteMapping("/users/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> delUser(@PathVariable long id){if(id==1)throw new IllegalArgumentException("内置管理员不能删除");jdbc.sql("DELETE FROM sys_user WHERE id=:id").param("id",id).update();return ApiResponse.ok();}
 @Operation(summary="强制用户全部设备退出") @PostMapping("/users/{id}/force-logout") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> forceLogout(@PathVariable long id){String username=jdbc.sql("SELECT username FROM sys_user WHERE id=:id").param("id",id).query(String.class).optional().orElseThrow(()->new IllegalArgumentException("用户不存在"));return ApiResponse.ok(Map.of("sessions",redis.forceLogout(username)));}
 private void setUserRoles(long id,List<Long> ids){jdbc.sql("DELETE FROM sys_user_role WHERE user_id=:id").param("id",id).update();if(ids!=null)ids.forEach(r->jdbc.sql("INSERT INTO sys_user_role(user_id,role_id) VALUES(:u,:r)").param("u",id).param("r",r).update());}

 @GetMapping("/roles") @PreAuthorize("hasAuthority('system:role:list')") ApiResponse<?> roles(){var rows=jdbc.sql("SELECT * FROM sys_role ORDER BY id").query().listOfRows();rows.forEach(x->x.put("menu_ids",jdbc.sql("SELECT menu_id FROM sys_role_menu WHERE role_id=:id").param("id",x.get("id")).query(Long.class).list()));return ApiResponse.ok(rows);}
 @PostMapping("/roles") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") @Transactional ApiResponse<?> addRole(@Valid @RequestBody RoleForm f){long id=jdbc.sql("INSERT INTO sys_role(name,code,description,status) VALUES(:n,:c,:d,:s) RETURNING id").param("n",f.name()).param("c",f.code()).param("d",f.description()).param("s",f.status()==null||f.status()).query(Long.class).single();setRoleMenus(id,f.menuIds());return ApiResponse.ok(Map.of("id",id));}
 @PutMapping("/roles/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") @Transactional ApiResponse<?> editRole(@PathVariable long id,@Valid @RequestBody RoleForm f){jdbc.sql("UPDATE sys_role SET name=:n,code=:c,description=:d,status=:s,updated_at=now() WHERE id=:id").param("n",f.name()).param("c",f.code()).param("d",f.description()).param("s",f.status()==null||f.status()).param("id",id).update();setRoleMenus(id,f.menuIds());return ApiResponse.ok();}
 @DeleteMapping("/roles/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> delRole(@PathVariable long id){if(id==1)throw new IllegalArgumentException("超级管理员角色不能删除");jdbc.sql("DELETE FROM sys_role WHERE id=:id").param("id",id).update();return ApiResponse.ok();}
 private void setRoleMenus(long id,List<Long> ids){jdbc.sql("DELETE FROM sys_role_menu WHERE role_id=:id").param("id",id).update();if(ids!=null)ids.forEach(m->jdbc.sql("INSERT INTO sys_role_menu(role_id,menu_id) VALUES(:r,:m)").param("r",id).param("m",m).update());}

 @GetMapping("/menus") @PreAuthorize("hasAuthority('system:menu:list')") ApiResponse<?> menus(){return ApiResponse.ok(jdbc.sql("SELECT * FROM sys_menu ORDER BY sort_order,id").query().listOfRows());}
 @PostMapping("/menus") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> addMenu(@Valid @RequestBody MenuForm f){long id=jdbc.sql("INSERT INTO sys_menu(parent_id,name,path,icon,permission,type,sort_order,visible) VALUES(:p,:n,:pa,:i,:pe,:t,:s,:v) RETURNING id").param("p",f.parentId()).param("n",f.name()).param("pa",f.path()).param("i",f.icon()).param("pe",f.permission()).param("t",f.type()==null?"MENU":f.type()).param("s",f.sortOrder()==null?0:f.sortOrder()).param("v",f.visible()==null||f.visible()).query(Long.class).single();return ApiResponse.ok(Map.of("id",id));}
 @PutMapping("/menus/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> editMenu(@PathVariable long id,@Valid @RequestBody MenuForm f){jdbc.sql("UPDATE sys_menu SET parent_id=:p,name=:n,path=:pa,icon=:i,permission=:pe,type=:t,sort_order=:s,visible=:v,updated_at=now() WHERE id=:id").param("p",f.parentId()).param("n",f.name()).param("pa",f.path()).param("i",f.icon()).param("pe",f.permission()).param("t",f.type()).param("s",f.sortOrder()).param("v",f.visible()).param("id",id).update();return ApiResponse.ok();}
 @DeleteMapping("/menus/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> delMenu(@PathVariable long id){jdbc.sql("WITH RECURSIVE menu_tree AS (SELECT id FROM sys_menu WHERE id=:id UNION ALL SELECT m.id FROM sys_menu m JOIN menu_tree t ON m.parent_id=t.id) DELETE FROM sys_menu WHERE id IN (SELECT id FROM menu_tree)").param("id",id).update();return ApiResponse.ok();}

 @GetMapping("/departments") ApiResponse<?> depts(){return ApiResponse.ok(jdbc.sql("SELECT * FROM sys_department ORDER BY sort_order,id").query().listOfRows());}
 @PostMapping("/departments") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> addDept(@Valid @RequestBody DeptForm f){long id=jdbc.sql("INSERT INTO sys_department(parent_id,name,leader,phone,sort_order,status) VALUES(:p,:n,:l,:ph,:s,:st) RETURNING id").param("p",f.parentId()).param("n",f.name()).param("l",f.leader()).param("ph",f.phone()).param("s",f.sortOrder()==null?0:f.sortOrder()).param("st",f.status()==null||f.status()).query(Long.class).single();return ApiResponse.ok(Map.of("id",id));}
 @PutMapping("/departments/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> editDept(@PathVariable long id,@Valid @RequestBody DeptForm f){jdbc.sql("UPDATE sys_department SET parent_id=:p,name=:n,leader=:l,phone=:ph,sort_order=:s,status=:st,updated_at=now() WHERE id=:id").param("p",f.parentId()).param("n",f.name()).param("l",f.leader()).param("ph",f.phone()).param("s",f.sortOrder()).param("st",f.status()).param("id",id).update();return ApiResponse.ok();}
 @DeleteMapping("/departments/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") ApiResponse<?> delDept(@PathVariable long id){jdbc.sql("DELETE FROM sys_department WHERE id=:id").param("id",id).update();return ApiResponse.ok();}
}
