package com.rpa.financial_intelligence_system.controller;

import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper;
import com.rpa.financial_intelligence_system.common.ApiResponse;
import io.swagger.v3.oas.annotations.Operation; import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid; import jakarta.validation.constraints.*;
import org.flowable.engine.*; import org.flowable.engine.history.*; import org.flowable.engine.repository.*; import org.flowable.task.api.Task;
import org.flowable.bpmn.converter.BpmnXMLConverter; import org.flowable.bpmn.model.BpmnModel; import org.flowable.bpmn.model.UserTask;
import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication;
import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
import java.io.StringReader; import java.nio.charset.StandardCharsets; import java.util.*; import javax.xml.stream.XMLInputFactory;

@Tag(name="工作流",description="基于 Flowable BPMN 2.0 的流程设计、部署、运行与审批") @RestController @RequestMapping("/api/workflow")
public class WorkflowController {
 private final JdbcClient jdbc; private final ObjectMapper mapper; private final RepositoryService repository; private final RuntimeService runtime; private final TaskService tasks; private final HistoryService history; private final IdentityService identity;
 public WorkflowController(JdbcClient jdbc,ObjectMapper mapper,RepositoryService repository,RuntimeService runtime,TaskService tasks,HistoryService history,IdentityService identity){this.jdbc=jdbc;this.mapper=mapper;this.repository=repository;this.runtime=runtime;this.tasks=tasks;this.history=history;this.identity=identity;}
 record NodeReq(@NotBlank String name,String assignee){}
 record DefinitionReq(@NotBlank String processKey,@NotBlank String name,String description,@NotEmpty List<NodeReq> nodes,Boolean enabled,String bpmnXml){}
 record StartReq(@NotNull Long definitionId,@NotBlank String businessTitle,Map<String,Object> businessData){}
 record HandleReq(@NotBlank String action,String comment){}

 @Operation(summary="查询 BPMN 流程定义") @GetMapping("/definitions") @PreAuthorize("hasAuthority('workflow:list')") ApiResponse<?> definitions(){var rows=jdbc.sql("SELECT id,process_key,name,description,nodes::text nodes,enabled,bpmn_xml,deployment_id,process_definition_id,created_at,updated_at FROM wf_definition ORDER BY id DESC").query().listOfRows();rows.forEach(r->{r.put("nodes",parse((String)r.get("nodes")));r.put("engine","Flowable BPMN 2.0");});return ApiResponse.ok(rows);}
 @Operation(summary="创建并部署 BPMN 流程") @PostMapping("/definitions") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") @Transactional ApiResponse<?> add(@Valid @RequestBody DefinitionReq q,Authentication a){long id=jdbc.sql("INSERT INTO wf_definition(process_key,name,description,nodes,enabled,created_by) VALUES(:k,:n,:d,cast(:nodes as jsonb),:e,:u) RETURNING id").param("k",q.processKey()).param("n",q.name()).param("d",q.description()).param("nodes",json(q.nodes())).param("e",q.enabled()==null||q.enabled()).param("u",uid(a)).query(Long.class).single();deploy(id,q);return ApiResponse.ok(Map.of("id",id));}
 @Operation(summary="修改并重新部署 BPMN 流程") @PutMapping("/definitions/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") @Transactional ApiResponse<?> edit(@PathVariable long id,@Valid @RequestBody DefinitionReq q){jdbc.sql("UPDATE wf_definition SET process_key=:k,name=:n,description=:d,nodes=cast(:nodes as jsonb),enabled=:e,updated_at=now() WHERE id=:id").param("k",q.processKey()).param("n",q.name()).param("d",q.description()).param("nodes",json(q.nodes())).param("e",q.enabled()==null||q.enabled()).param("id",id).update();deploy(id,q);return ApiResponse.ok();}
 @Operation(summary="删除 BPMN 流程定义") @DeleteMapping("/definitions/{id}") @PreAuthorize("hasAuthority('ROLE_SUPER_ADMIN')") @Transactional ApiResponse<?> delete(@PathVariable long id){var d=definition(id);String pd=(String)d.get("process_definition_id");if(pd!=null&&history.createHistoricProcessInstanceQuery().processDefinitionId(pd).count()>0)throw new IllegalArgumentException("该流程已有运行记录，不能删除");String deployment=(String)d.get("deployment_id");if(deployment!=null)repository.deleteDeployment(deployment);jdbc.sql("DELETE FROM wf_definition WHERE id=:id").param("id",id).update();return ApiResponse.ok();}
 @Operation(summary="发起 Flowable 流程实例") @PostMapping("/instances") @PreAuthorize("hasAuthority('workflow:list')") ApiResponse<?> start(@Valid @RequestBody StartReq q,Authentication a){var d=definition(q.definitionId());if(!Boolean.TRUE.equals(d.get("enabled")))throw new IllegalArgumentException("流程已停用");String pd=(String)d.get("process_definition_id");if(pd==null)throw new IllegalArgumentException("流程尚未发布");var vars=new LinkedHashMap<String,Object>();if(q.businessData()!=null)vars.putAll(q.businessData());vars.put("businessTitle",q.businessTitle());vars.put("starterUsername",a.getName());identity.setAuthenticatedUserId(a.getName());try{var p=runtime.startProcessInstanceById(pd,q.businessTitle(),vars);return ApiResponse.ok(Map.of("id",p.getId(),"processDefinitionId",pd));}finally{identity.setAuthenticatedUserId(null);}}
 @Operation(summary="查询 Flowable 流程实例") @GetMapping("/instances") @PreAuthorize("hasAuthority('workflow:list')") ApiResponse<?> instances(Authentication a){var query=history.createHistoricProcessInstanceQuery().includeProcessVariables().orderByProcessInstanceStartTime().desc();List<HistoricProcessInstance> list=isAdmin(a)?query.list():query.startedBy(a.getName()).list();List<Map<String,Object>> out=new ArrayList<>();for(var p:list){var m=new LinkedHashMap<String,Object>();m.put("id",p.getId());m.put("business_title",p.getProcessVariables().getOrDefault("businessTitle",p.getBusinessKey()));m.put("definition_name",definitionName(p.getProcessDefinitionId()));m.put("starter_username",p.getStartUserId());Task current=tasks.createTaskQuery().processInstanceId(p.getId()).singleResult();m.put("current_node_name",current==null?null:current.getName());m.put("status",p.getEndTime()==null?"RUNNING":p.getDeleteReason()!=null&&p.getDeleteReason().startsWith("REJECTED")?"REJECTED":"APPROVED");m.put("started_at",p.getStartTime());m.put("finished_at",p.getEndTime());out.add(m);}return ApiResponse.ok(out);}
 @Operation(summary="查询 Flowable 待办任务") @GetMapping("/tasks") @PreAuthorize("hasAuthority('workflow:task')") ApiResponse<?> taskList(Authentication a,@RequestParam(defaultValue="PENDING")String status){var query=tasks.createTaskQuery().includeProcessVariables().orderByTaskCreateTime().desc();List<Task> list=isAdmin(a)?query.list():query.taskCandidateOrAssigned(a.getName()).list();List<Map<String,Object>> out=new ArrayList<>();for(Task t:list){var m=new LinkedHashMap<String,Object>();m.put("id",t.getId());m.put("instance_id",t.getProcessInstanceId());m.put("business_title",t.getProcessVariables().get("businessTitle"));m.put("definition_name",definitionName(t.getProcessDefinitionId()));m.put("node_name",t.getName());m.put("starter_username",t.getProcessVariables().get("starterUsername"));m.put("assignee_username",t.getAssignee());m.put("status","PENDING");m.put("created_at",t.getCreateTime());out.add(m);}return ApiResponse.ok(out);}
 @Operation(summary="完成或驳回 Flowable 审批任务") @PostMapping("/tasks/{id}/handle") @PreAuthorize("hasAuthority('workflow:task')") ApiResponse<?> handle(@PathVariable String id,@Valid @RequestBody HandleReq q,Authentication a){Task t=tasks.createTaskQuery().taskId(id).singleResult();if(t==null)throw new IllegalArgumentException("任务不存在或已经处理");if(!isAdmin(a)&&!a.getName().equals(t.getAssignee()))throw new IllegalArgumentException("无权处理该任务");if(q.comment()!=null&&!q.comment().isBlank())tasks.addComment(id,t.getProcessInstanceId(),q.comment());if("APPROVE".equalsIgnoreCase(q.action()))tasks.complete(id,Map.of("approved",true,"lastApprover",a.getName()));else if("REJECT".equalsIgnoreCase(q.action()))runtime.deleteProcessInstance(t.getProcessInstanceId(),"REJECTED:"+Optional.ofNullable(q.comment()).orElse(""));else throw new IllegalArgumentException("审批动作不正确");return ApiResponse.ok();}

 private void deploy(long id,DefinitionReq q){String xml=bpmn(q);Deployment deployment=repository.createDeployment().name(q.name()).key(q.processKey()).addBytes(q.processKey()+".bpmn20.xml",xml.getBytes(StandardCharsets.UTF_8)).deploy();ProcessDefinition pd=repository.createProcessDefinitionQuery().deploymentId(deployment.getId()).singleResult();jdbc.sql("UPDATE wf_definition SET bpmn_xml=:x,deployment_id=:d,process_definition_id=:p WHERE id=:id").param("x",xml).param("d",deployment.getId()).param("p",pd.getId()).param("id",id).update();}
 private String bpmn(DefinitionReq q){
  if(q.bpmnXml()==null||q.bpmnXml().isBlank())return legacyBpmn(q);
  if(!q.processKey().matches("[A-Za-z_][A-Za-z0-9_-]*"))throw new IllegalArgumentException("流程标识只能包含字母、数字、下划线和中划线，且不能以数字开头");
  try{
   XMLInputFactory factory=XMLInputFactory.newFactory();factory.setProperty(XMLInputFactory.SUPPORT_DTD,false);factory.setProperty("javax.xml.stream.isSupportingExternalEntities",false);
   BpmnXMLConverter converter=new BpmnXMLConverter();BpmnModel model=converter.convertToBpmnModel(factory.createXMLStreamReader(new StringReader(q.bpmnXml())));var process=model.getMainProcess();
   if(process==null)throw new IllegalArgumentException("未找到可执行流程");
   if(process.findFlowElementsOfType(UserTask.class).isEmpty())throw new IllegalArgumentException("流程中至少需要一个用户审批任务");
   process.setId(q.processKey());process.setName(q.name());process.setExecutable(true);model.setTargetNamespace("http://finsight.local/workflow");
   return new String(converter.convertToXML(model),StandardCharsets.UTF_8);
  }catch(IllegalArgumentException e){throw e;}catch(Exception e){throw new IllegalArgumentException("BPMN 流程校验失败："+e.getMessage());}
 }
 private String legacyBpmn(DefinitionReq q){StringBuilder x=new StringBuilder("<?xml version=\"1.0\" encoding=\"UTF-8\"?><definitions xmlns=\"http://www.omg.org/spec/BPMN/20100524/MODEL\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:flowable=\"http://flowable.org/bpmn\" targetNamespace=\"http://finsight.local/workflow\"><process id=\"").append(esc(q.processKey())).append("\" name=\"").append(esc(q.name())).append("\" isExecutable=\"true\"><startEvent id=\"start\" name=\"发起人\"/>");String previous="start";for(int i=0;i<q.nodes().size();i++){NodeReq n=q.nodes().get(i);String node="task_"+(i+1);x.append("<userTask id=\"").append(node).append("\" name=\"").append(esc(n.name())).append("\" flowable:assignee=\"").append(esc(n.assignee())).append("\"/><sequenceFlow id=\"flow_").append(i).append("\" sourceRef=\"").append(previous).append("\" targetRef=\"").append(node).append("\"/>");previous=node;}x.append("<endEvent id=\"end\" name=\"流程结束\"/><sequenceFlow id=\"flow_end\" sourceRef=\"").append(previous).append("\" targetRef=\"end\"/></process></definitions>");return x.toString();}
 private Map<String,Object> definition(long id){var rows=jdbc.sql("SELECT * FROM wf_definition WHERE id=:id").param("id",id).query().listOfRows();if(rows.isEmpty())throw new IllegalArgumentException("流程定义不存在");return rows.getFirst();}
 private String definitionName(String processDefinitionId){ProcessDefinition p=repository.createProcessDefinitionQuery().processDefinitionId(processDefinitionId).singleResult();return p==null?"-":p.getName();}
 private List<Map<String,Object>> parse(String value){try{return mapper.readValue(value,new TypeReference<>(){});}catch(Exception e){return List.of();}}
 private String json(Object value){try{return mapper.writeValueAsString(value);}catch(Exception e){throw new IllegalArgumentException("数据格式错误");}}
 private String esc(String s){return s==null?"":s.replace("&","&amp;").replace("\"","&quot;").replace("<","&lt;").replace(">","&gt;");}
 private long uid(Authentication a){return jdbc.sql("SELECT id FROM sys_user WHERE username=:u").param("u",a.getName()).query(Long.class).single();}
 private boolean isAdmin(Authentication a){return a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_SUPER_ADMIN"));}
}
